import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  BarChart3,
  CalendarDays,
  ChevronDown,
  CircleAlert,
  Download,
  FileBarChart,
  FileDown,
  Menu,
  SlidersHorizontal,
  Wrench,
} from "lucide-react";
import { AdminSidebar } from "@/components/AdminSidebar";
import ThemedSelect from "../components/ThemedSelect.jsx";
import { useAuth } from "../context/AuthContext.jsx";
import { SAMPLE_DATA, CATEGORY_LABELS, STATUS_LABELS } from "@/data/complaints";
import { SAMPLE_RESIDENTS } from "@/data/residents";
import { DATE_RANGES, REPORT_TYPES, SAMPLE_REPORTS } from "@/data/reports";

const CATEGORY_KEYS = ["septic_tank", "garbage", "street_lights", "road_damage", "noise", "water_supply", "other"];
const STATUS_KEYS = ["pending", "in_progress", "resolved"];
const STATUS_COLORS = {
  pending: "var(--danger)",
  in_progress: "var(--warning)",
  resolved: "var(--success)",
};

function formatDate(value) {
  return new Intl.DateTimeFormat("en-US", { month: "short", day: "2-digit", year: "numeric" }).format(new Date(value));
}

function downloadReportsCsv(reports, fileName) {
  const escapeCell = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
  const rows = [
    ["Report Name", "Type", "Generated By", "Date"],
    ...reports.map((report) => [report.report_name, report.type, report.generated_by, formatDate(report.created_at)]),
  ];
  const content = rows.map((row) => row.map(escapeCell).join(",")).join("\r\n");
  const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${fileName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}.csv`;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}

function DonutChart({ counts }) {
  const total = STATUS_KEYS.reduce((sum, key) => sum + counts[key], 0);
  const radius = 42;
  const circumference = 2 * Math.PI * radius;
  let offset = 0;

  return (
    <div className="relative h-36 w-36 shrink-0">
      <svg viewBox="0 0 112 112" className="h-full w-full -rotate-90" aria-label={`Complaint status breakdown, ${total} total`} role="img">
        <circle cx="56" cy="56" r={radius} fill="none" stroke="var(--muted)" strokeWidth="14" />
        {STATUS_KEYS.map((key) => {
          const length = total ? (counts[key] / total) * circumference : 0;
          const circle = (
            <circle
              key={key}
              cx="56"
              cy="56"
              r={radius}
              fill="none"
              stroke={STATUS_COLORS[key]}
              strokeWidth="14"
              strokeDasharray={`${length} ${circumference - length}`}
              strokeDashoffset={-offset}
            />
          );
          offset += length;
          return circle;
        })}
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="font-display text-2xl font-bold">{total}</span>
        <span className="text-[10px] text-muted-foreground">Total</span>
      </div>
    </div>
  );
}

export default function AdminReports() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);
  const [dateRange, setDateRange] = useState("180");
  const [reportType, setReportType] = useState("All");

  const categoryCounts = useMemo(
    () => Object.fromEntries(CATEGORY_KEYS.map((key) => [key, SAMPLE_DATA.filter((item) => item.category === key).length])),
    [],
  );
  const statusCounts = useMemo(
    () => Object.fromEntries(STATUS_KEYS.map((key) => [key, SAMPLE_DATA.filter((item) => item.status === key).length])),
    [],
  );
  const tanksWithReadings = SAMPLE_RESIDENTS.filter((resident) => resident.fill_level != null);
  const averageFill = tanksWithReadings.length
    ? Math.round(tanksWithReadings.reduce((sum, resident) => sum + resident.fill_level, 0) / tanksWithReadings.length)
    : 0;
  const now = new Date();
  const desludgingEvents = SAMPLE_DATA.filter((item) => {
    if (item.category !== "septic_tank" || item.status !== "resolved" || !item.resolved_at) return false;
    const resolved = new Date(item.resolved_at);
    return resolved.getUTCFullYear() === now.getUTCFullYear() && resolved.getUTCMonth() === now.getUTCMonth();
  }).length;
  const unresolved = statusCounts.pending + statusCounts.in_progress;
  const maxCategory = Math.max(...Object.values(categoryCounts), 1);

  const visibleReports = useMemo(() => {
    const cutoff = dateRange === "all" ? null : Date.now() - Number(dateRange) * 24 * 60 * 60 * 1000;
    return SAMPLE_REPORTS.filter((report) => {
      const inRange = cutoff == null || new Date(report.created_at).getTime() >= cutoff;
      const matchesType = reportType === "All" || report.type === reportType;
      return inRange && matchesType;
    });
  }, [dateRange, reportType]);

  const stats = [
    { label: "Total Reports Generated", value: SAMPLE_REPORTS.length, sub: "All recorded reports", icon: FileBarChart, chip: "bg-primary/15 text-primary" },
    { label: "Avg Community Fill Level", value: `${averageFill}%`, sub: `Across ${tanksWithReadings.length} tanks`, icon: BarChart3, chip: "bg-primary/15 text-primary" },
    { label: "Desludging Events", value: desludgingEvents, sub: "Resolved this month", icon: Wrench, chip: "bg-warning/15 text-warning" },
    { label: "Unresolved Complaints", value: unresolved, sub: "Pending or in progress", icon: CircleAlert, chip: "bg-danger/15 text-danger" },
  ];
  const signOut = async () => {
    await logout();
    navigate("/");
  };

  return (
    <div className="min-h-screen bg-background">
      <AdminSidebar open={menuOpen} setOpen={setMenuOpen} navigate={navigate} user={user} active="Reports" signOut={signOut} />
      <main className="min-w-0 flex-1 lg:ml-52">
        <header className="flex min-h-20 items-center gap-3 border-b border-border px-4 py-4 sm:px-7">
          <button type="button" onClick={() => setMenuOpen(true)} aria-label="Open menu" className="shrink-0 rounded-md border border-border p-2 lg:hidden"><Menu className="h-4 w-4" /></button>
          <div className="min-w-0">
            <p className="truncate text-[10px] text-muted-foreground sm:text-xs">Admin Portal › Reports</p>
            <h1 className="mt-1 font-display text-lg font-bold sm:text-xl">Reports &amp; Analytics</h1>
          </div>
        </header>
        <div className="px-5 py-6 md:px-8">

        <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {stats.map((stat) => (
            <article key={stat.label} className="rounded-lg border border-border bg-card p-4">
              <div className="flex items-start justify-between gap-3">
                <span className="text-sm text-muted-foreground">{stat.label}</span>
                <span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-md ${stat.chip}`}><stat.icon className="h-4 w-4" /></span>
              </div>
              <p className="mt-3 font-display text-3xl font-bold">{stat.value}</p>
              <p className="mt-1 text-xs text-muted-foreground">{stat.sub}</p>
            </article>
          ))}
        </div>

        <div className="mt-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
          <div className="flex flex-col gap-3 sm:flex-row">
            <label className="relative">
              <span className="sr-only">Date Range</span>
              <CalendarDays className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <ThemedSelect value={dateRange} onChange={setDateRange} options={DATE_RANGES.map((range) => ({ value: range.value, label: `Date Range: ${range.label}` }))} className="w-full sm:w-48" />
              <ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            </label>
            <label className="relative">
              <span className="sr-only">Report Type</span>
              <SlidersHorizontal className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <ThemedSelect value={reportType} onChange={setReportType} options={REPORT_TYPES.map((type) => ({ value: type, label: `Report Type: ${type}` }))} className="w-full sm:w-52" />
              <ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            </label>
          </div>
          <button type="button" disabled={visibleReports.length === 0} onClick={() => downloadReportsCsv(visibleReports, "SeptiGuard Reports")} className="flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50">
            <Download className="h-4 w-4" /> Export CSV
          </button>
        </div>

        <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_1fr]">
          <section className="rounded-lg border border-border bg-card p-5">
            <h2 className="text-base font-semibold">Complaints by Category</h2>
            <p className="mt-1 text-xs text-muted-foreground">Distribution across the seven complaint categories</p>
            <div className="mt-5 space-y-3">
              {CATEGORY_KEYS.map((key) => (
                <div key={key} className="grid grid-cols-[96px_1fr_24px] items-center gap-3 sm:grid-cols-[120px_1fr_28px]">
                  <span className="truncate text-xs">{CATEGORY_LABELS[key]}</span>
                  <div className="h-5 overflow-hidden rounded bg-muted">
                    <div className="h-full min-w-0 rounded bg-primary" style={{ width: `${(categoryCounts[key] / maxCategory) * 100}%` }} />
                  </div>
                  <span className="text-right text-xs font-medium">{categoryCounts[key]}</span>
                </div>
              ))}
            </div>
          </section>

          <section className="rounded-lg border border-border bg-card p-5">
            <h2 className="text-base font-semibold">Complaint Status Breakdown</h2>
            <p className="mt-1 text-xs text-muted-foreground">Current status of all {SAMPLE_DATA.length} complaints</p>
            <div className="mt-6 flex flex-col items-center justify-center gap-6 sm:flex-row">
              <DonutChart counts={statusCounts} />
              <div className="w-full max-w-xs space-y-3">
                {STATUS_KEYS.map((key) => {
                  const percent = SAMPLE_DATA.length ? Math.round((statusCounts[key] / SAMPLE_DATA.length) * 100) : 0;
                  return (
                    <div key={key} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 text-sm">
                      <span className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${key === "pending" ? "bg-danger" : key === "in_progress" ? "bg-warning" : "bg-success"}`} />{STATUS_LABELS[key]}</span>
                      <strong>{statusCounts[key]}</strong>
                      <span className="w-9 text-right text-xs text-muted-foreground">{percent}%</span>
                    </div>
                  );
                })}
              </div>
            </div>
          </section>
        </div>

        <section className="mt-6 overflow-hidden rounded-lg border border-border bg-card">
          <div className="p-5">
            <h2 className="text-base font-semibold">Recent Reports</h2>
            <p className="mt-1 text-xs text-muted-foreground">Saved report records for the selected period</p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[760px] text-sm">
              <thead>
                <tr className="border-y border-border text-left text-[11px] uppercase text-muted-foreground">
                  <th className="px-5 py-3 font-medium">Report Name</th>
                  <th className="px-5 py-3 font-medium">Type</th>
                  <th className="px-5 py-3 font-medium">Generated By</th>
                  <th className="px-5 py-3 font-medium">Date</th>
                  <th className="px-5 py-3 text-right font-medium">Download</th>
                </tr>
              </thead>
              <tbody>
                {visibleReports.map((report) => (
                  <tr key={report.id} className="border-b border-border last:border-0 hover:bg-muted/40">
                    <td className="px-5 py-4"><span className="flex items-center gap-2 font-medium"><FileBarChart className="h-4 w-4 shrink-0 text-primary" />{report.report_name}</span></td>
                    <td className="px-5 py-4 text-muted-foreground">{report.type}</td>
                    <td className="px-5 py-4">{report.generated_by}</td>
                    <td className="px-5 py-4 text-muted-foreground">{formatDate(report.created_at)}</td>
                    <td className="px-5 py-4 text-right">
                      <button type="button" onClick={() => downloadReportsCsv([report], report.report_name)} aria-label={`Download ${report.report_name} as CSV`} title="Download CSV" className="rounded-md p-2 text-primary hover:bg-primary/10"><FileDown className="h-4 w-4" /></button>
                    </td>
                  </tr>
                ))}
                {visibleReports.length === 0 && <tr><td colSpan={5} className="p-10 text-center"><p className="text-sm font-medium">No reports match these filters</p><p className="mt-1 text-xs text-muted-foreground">Try a wider date range or a different report type.</p><button type="button" onClick={() => { setDateRange("180"); setReportType("All"); }} className="mt-3 rounded-md border border-border px-3 py-2 text-xs font-medium hover:bg-muted">Reset filters</button></td></tr>}
              </tbody>
            </table>
          </div>
        </section>
        </div>
      </main>
    </div>
  );
}