import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Activity, ArrowRight, Bell, Bot, CalendarDays, Check, Droplets, Eye, FileWarning, Home, LogOut, MapPin, Menu, Settings, ShieldCheck, UserRound, Wrench, Zap } from "lucide-react";
import { useAuth } from "../context/AuthContext.jsx";

const SAMPLE_DATA = { level: 70, daysUntilFull: 12, location: "Blk 12, Lot 4 · Broadway Hagdan", alerts: [
  { icon: FileWarning, title: "Tank level reached 70%", detail: "Consider scheduling maintenance soon", tag: "Warning", tone: "warning", time: "2h ago" },
  { icon: Bot, title: "AI prediction updated", detail: "Estimated 12 days until critical level", tag: "Info", tone: "primary", time: "6h ago" },
  { icon: Check, title: "Sensor calibration complete", detail: "All sensors operating within normal range", tag: "Normal", tone: "success", time: "Yesterday" },
  { icon: Zap, title: "Firmware updated to v2.1.4", detail: "Improved accuracy and battery efficiency", tag: "System", tone: "muted", time: "2 days ago" },
] };
const NAV = [{icon:Home,label:"Dashboard",path:"/dashboard",active:true},{icon:Activity,label:"Monitoring",path:"/monitor"},{icon:Bot,label:"Predict",path:"/predict"},{icon:FileWarning,label:"Complaints",path:"/complaints"},{icon:Wrench,label:"Maintain",path:"/maintain"},{icon:Bell,label:"Alerts",path:"/alerts"},{icon:UserRound,label:"Profile",path:"/profile"}];

export default function Dashboard() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [open,setOpen]=useState(false); const first=user?.name?.split(" ")[0] ?? "Resident";
  const soon=(name)=>window.alert(`${name} will be connected in the next step.`);
  const signOut=async()=>{await logout(); navigate("/");};
  return <div className="min-h-screen bg-background text-foreground lg:flex">
    <aside className={`${open?"flex":"hidden"} fixed inset-y-0 left-0 z-40 w-24 flex-col border-r border-border bg-card px-2 py-5 lg:flex`}>
      <div className="mb-5 flex justify-center"><div className="flex h-11 w-11 items-center justify-center rounded-lg border border-primary/40 bg-primary/10"><ShieldCheck className="h-5 w-5 text-primary"/></div></div>
      <nav className="flex flex-1 flex-col gap-1">{NAV.map(x=><button key={x.label} onClick={()=>x.path?(setOpen(false),navigate(x.path)):soon(x.label)} className={`relative flex h-14 flex-col items-center justify-center gap-1 rounded-md text-[10px] ${x.active?"bg-primary font-medium text-primary-foreground":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}><x.icon className="h-4 w-4"/>{x.label}</button>)}</nav>
      <div className="flex flex-col items-center gap-2 border-t border-border pt-4"><div className="flex h-9 w-9 items-center justify-center rounded-full border border-primary text-[10px] font-semibold">{first.slice(0,2).toUpperCase()}</div><button onClick={signOut} title="Sign out" className="p-2 text-muted-foreground hover:text-danger"><LogOut className="h-4 w-4"/></button></div>
    </aside>{open&&<button className="fixed inset-0 z-30 bg-background/80 lg:hidden" onClick={()=>setOpen(false)}/>}
    <div className="min-w-0 flex-1 lg:ml-24"><header className="flex h-20 items-center justify-between border-b border-border px-4 sm:px-7"><div className="flex items-center gap-3"><button className="rounded-md border border-border p-2 lg:hidden" onClick={()=>setOpen(true)}><Menu className="h-4 w-4"/></button><div><p className="text-xs text-muted-foreground">Resident Portal › Dashboard</p><h1 className="mt-1 font-display text-xl font-bold">Dashboard</h1></div></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-xs text-muted-foreground sm:flex"><span className="h-2 w-2 rounded-full bg-success"/>Sensor Online</div><button onClick={()=>soon("Notifications")} className="rounded-md border border-border p-2"><Bell className="h-4 w-4"/></button><button onClick={()=>soon("Settings")} className="rounded-md border border-border p-2"><Settings className="h-4 w-4"/></button></div></header>
    <main className="mx-auto max-w-[1440px] space-y-5 p-4 sm:p-7">
      <section className="flex flex-col justify-between gap-5 rounded-lg border border-primary/20 bg-primary/15 p-5 sm:flex-row sm:items-center"><div><div className="mb-2 flex items-center gap-2 text-xs text-primary"><span className="rounded border border-primary/30 px-2 py-0.5 font-semibold uppercase">Sample data</span><span>Wednesday, March 12</span></div><h2 className="font-display text-xl font-bold">Welcome back, {first}!</h2><p className="mt-1 text-sm text-muted-foreground">Your septic tank is being monitored 24/7. Here&apos;s a quick overview.</p></div><div className="flex min-w-60 items-center gap-3 rounded-md border border-primary/15 bg-background/45 px-4 py-3"><MapPin className="h-5 w-5 text-primary"/><div><p className="text-[9px] uppercase text-muted-foreground">Location</p><p className="text-xs font-medium">{SAMPLE_DATA.location}</p></div></div></section>
      <div className="grid gap-5 xl:grid-cols-[1.55fr_0.9fr]"><section className="rounded-lg border border-border bg-card p-5 sm:p-6"><div className="flex justify-between gap-3"><div><h2 className="font-display font-semibold">Tank Status</h2><p className="mt-1 text-xs text-muted-foreground">Real-time fill level from IoT sensor</p></div><span className="h-fit rounded-full border border-warning/30 bg-warning/10 px-3 py-1 text-xs font-semibold text-warning">Warning</span></div><div className="mt-5 grid items-center gap-7 md:grid-cols-[190px_1fr]"><div className="relative mx-auto h-44 w-44"><svg viewBox="0 0 120 120" className="h-full w-full -rotate-90"><circle cx="60" cy="60" r="50" fill="none" stroke="currentColor" strokeWidth="9" className="text-muted"/><circle cx="60" cy="60" r="50" fill="none" stroke="currentColor" strokeWidth="9" strokeLinecap="round" strokeDasharray="220 314" className="text-warning"/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-[9px] uppercase text-muted-foreground">Fill level</span><strong className="font-display text-4xl">70%</strong><span className="text-[10px] text-muted-foreground">of capacity</span></div></div><div className="space-y-2"><Level color="bg-success" label="0–40% Normal" note="Safe"/><Level color="bg-warning" label="41–75% Warning" note="Current" active/><Level color="bg-danger" label="76–100% Critical" note="Action needed"/><div className="flex gap-3 rounded-md border border-primary/35 bg-primary/10 p-3"><Bot className="h-4 w-4 text-primary"/><div><p className="text-xs font-semibold text-primary">AI Prediction</p><p className="mt-1 text-[11px] text-muted-foreground">Tank will reach critical level in ~12 days</p></div></div></div></div></section>
      <div className="space-y-5"><div className="grid grid-cols-3 gap-3"><Metric icon={Droplets} label="Current level" value="70%" note="+5% this week"/><Metric icon={CalendarDays} label="Days until full" value="12" note="days remaining"/><Metric icon={Wrench} label="Last pumped" value="Jan 8" note="63 days ago"/></div><section className="rounded-lg border border-border bg-card p-5"><h2 className="font-display font-semibold">Quick Actions</h2><p className="mt-1 text-xs text-muted-foreground">Common tasks for your tank</p><div className="mt-4 space-y-2"><Action icon={Eye} label="View Detailed Report" primary onClick={()=>soon("Detailed reports")}/><Action icon={FileWarning} label="File a Complaint" onClick={()=>soon("Complaints")}/><Action icon={CalendarDays} label="Schedule Maintenance" onClick={()=>soon("Maintenance scheduling")}/></div></section></div></div>
      <section className="rounded-lg border border-border bg-card p-5 sm:p-6"><div className="flex items-end justify-between"><div><h2 className="font-display font-semibold">Recent Alerts</h2><p className="mt-1 text-xs text-muted-foreground">Latest notifications from your sensor network</p></div><button onClick={()=>soon("All alerts")} className="flex items-center gap-1 text-xs text-primary">View all <ArrowRight className="h-3 w-3"/></button></div><div className="mt-5 space-y-2">{SAMPLE_DATA.alerts.map(a=><Alert key={a.title} {...a}/>)}</div></section>
    </main></div></div>;
}
function Level({color,label,note,active}){return <div className={`flex justify-between rounded-md border px-3 py-3 text-xs ${active?"border-warning/35 bg-warning/10":"border-transparent bg-muted/50"}`}><span className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${color}`}/>{label}</span><span className={active?"text-warning":"text-muted-foreground"}>{note}</span></div>}
function Metric({icon:Icon,label,value,note}){return <div className="min-w-0 rounded-lg border border-border bg-card p-4"><Icon className="h-4 w-4 text-primary"/><p className="mt-4 truncate text-[9px] uppercase text-muted-foreground">{label}</p><p className="mt-2 font-display text-xl font-bold">{value}</p><p className="mt-3 text-[9px] text-muted-foreground">{note}</p></div>}
function Action({icon:Icon,label,primary,onClick}){return <button onClick={onClick} className={`flex h-10 w-full items-center justify-between rounded-md px-3 text-sm font-medium ${primary?"bg-primary text-primary-foreground":"bg-secondary text-secondary-foreground"}`}><span className="flex items-center gap-2"><Icon className="h-4 w-4"/>{label}</span><ArrowRight className="h-4 w-4"/></button>}
function Alert({icon:Icon,title,detail,tag,tone,time}){const colors={warning:"border-warning/30 bg-warning/10 text-warning",primary:"border-transparent bg-muted/55 text-primary",success:"border-transparent bg-muted/55 text-success",muted:"border-transparent bg-muted/55 text-muted-foreground"};return <div className={`flex items-center gap-3 rounded-md border p-3 ${colors[tone]}`}><div className="flex h-9 w-9 items-center justify-center rounded-md bg-background/40"><Icon className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><p className="text-xs font-semibold text-foreground">{title}</p><span className="text-[9px]">{tag}</span></div><p className="mt-1 truncate text-[10px] text-muted-foreground">{detail}</p></div><span className="text-[10px] text-muted-foreground">{time}</span></div>}